name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: my_project_sch
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysql -u root -p123456 -e 'SELECT 1'"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify MySQL Service
      run: |
        echo "Checking MySQL connectivity..."
        until mysql -h mysql -u root -p123456 -e 'SHOW DATABASES'; do
          echo 'Waiting for MySQL...'
          sleep 10
        done
        echo 'MySQL is up and running!'

    - name: Print MySQL logs if the connection fails
      if: failure()
      run: docker logs ${{ job.services.mysql.id }}

    - name: Build and Test with Maven Wrapper
      run: |
        ./mvnw clean verify
      env:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        DATABASE_NAME: my_project_sch
