name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: my_project_sch
        ports:
          - 3306:3306

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Print network configuration
      run: |
        echo "Listing all hosts..."
        cat /etc/hosts

    - name: Test MySQL Connection Early
      run: |
        echo "Attempting to connect to MySQL..."
        mysql -h mysql -u root -p123456 -e "SHOW DATABASES;"
        if [ $? -ne 0 ]; then
          echo "Initial connection failed. Attempting to connect repeatedly..."
          for i in {1..5}; do
            mysql -h mysql -u root -p123456 -e 'SHOW DATABASES' && break
            echo "Retry $i: MySQL not available yet. Retrying in 5 seconds..."
            sleep 5
          done
        fi

    - name: Build and Test with Maven Wrapper
      run: |
        ./mvnw clean verify
      env:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        DATABASE_NAME: my_project_sch
