name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: my_project_sch
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify MySQL Service
      run: |
        until mysqladmin ping -h"mysql" -P"3306" --silent; do
          echo 'Waiting for MySQL...'
          sleep 1
        done
        echo 'MySQL is up and running!'

    - name: Build and Test with Maven Wrapper
      run: |
        ./mvnw clean verify
      env:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        DATABASE_NAME: my_project_sch
