name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: my_project_sch
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin -h 10.0.0.1 -u root -p123456 ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Print MySQL service logs
      run: docker logs ${{ job.services.mysql.id }}

    - name: Verify MySQL Service
      run: |
        echo "Checking MySQL connectivity..."
        for i in {1..10}; do
          if mysql -h 10.0.0.1 -u root -p123456 -e 'SHOW DATABASES'; then
            echo 'MySQL is up and running!'
            break
          fi
          echo "MySQL not yet available. Retrying in 10 seconds..."
          sleep 10
        done
        if [[ $i -eq 10 ]]; then
          echo "Error: Could not connect to MySQL after 10 retries."
          exit 1
        fi

    - name: Build and Test with Maven Wrapper
      run: |
        ./mvnw clean verify
      env:
        MYSQL_HOST: 10.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        DATABASE_NAME: my_project_sch
